### PR TITLE
update to juttle 0.7.0

### PR DESCRIPTION
**Pull request by demmer**
Bump the package.json to the new adapter API.
Add a check for nested fields in the query parsing.
Update the changelog for the pending release.

### CODE REVIEW

**Comment by demmer** [comment]
@mstemm

**Comment by mstemm** [comment]
lgtm.

**Comment by dmajda** [comment]
I think a more appropriate place for the check would be `Linter`. It is scans the filter AST before everything else with an explicit purpose to validate it and there are already similar checks there.

**Comment by demmer** [comment]
I moved the check to the linter as suggested by @dmajda. Will merge and publish now.

**Pull request merged**
