### PR TITLE
Disallow filtering on null

### PR DESCRIPTION
**Pull request by bkutil**
It is not consistently supported by influx DB

Fixes: #73

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmehra

**Comment by dmehra** [comment]
let's add another test for "field != null". Also, let's get to green :)

**Comment by bkutil** [comment]
Added the `field != null` test, and removed the offending one (testing for an error doesn't make sense on that level).

**Comment by dmehra** [comment]
+1

**Pull request merged**
