### PR TITLE
Add integration tests covering regexes

### PR DESCRIPTION
**Pull request by bkutil**

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmehra

**Comment by bkutil** [comment]
@demmer, @dmajda - it looks like Daria found an interesting issue - the influx does support regexes/globs on tags, but it doesn't filter values (integers or strings). What do you think would be the correct approach here?

I see three potential approaches (from these, 2. seems the least problematic):

1. Try to type-annotate the tags/values (store the metadata/or use nested points so that we can distinguish between tags/ and values). Then throw exception for tags, but not for values.
2. Fallback to what influx does - silently return empty result set for regexes on values.
3. Disallow regex/glob filtering - which wouldn't work as we now filter on `name`.

Any other options?

**Comment by demmer** [comment]
I agree that 2 seems the least bad.

**Comment by dmajda** [comment]
I think our guiding principle should be to match the underlying database’s behavior as closely as possible without breaking our own abstractions. That suggests 2.

**Comment by dmehra** [comment]
We are agreed on option 2, then. 

For a comparison point, we ended up with something similar in elastic-adapter, where you get different results from read filters `fieldname = value` and from `reduce by` depending on whether your ES schema has analyzed or not_analyzed fields. The result sets coming back are not necessarily empty, just... different. We have started emitting a warning for reducing on analyzed field there, it was a borderline call whether to do that or silently let ES do what it will, since the basic assumption is the user knows their schema and behaviors that fall out of it. With influx-adapter, it seems reasonable to expect that the user would know what they defined to be tags vs values, as that is a cornerstone of your InfluxDB schema, and would not expect some operations to work on values.

**Comment by dmehra** [comment]
+1 on tests here, once you unskip the tests on values which should expect empty set back, per Option 2.

Side note: do we need a test on the `in` operator for tags? currently only values are covered. `tag in [ 'foo', 'bar' ]` is what i'm thinking. 
https://github.com/juttle/juttle-influx-adapter/blob/regexes-globs-test/test/influx-integration.spec.js#L323

**Comment by dmehra** [comment]
Another side note: `Possibly bug in Influx` - are we filing an issue on them? Or on ourselves first, to investigate?
https://github.com/juttle/juttle-influx-adapter/blob/regexes-globs-test/test/influx-integration.spec.js#L303

**Comment by bkutil** [comment]
@dmehra - unskipped the tests that document the behavior.

> Side note: do we need a test on the in

It won't hurt, for documentation purposes.

> Another side note: Possibly bug in Influx

Added link to upstream issue in #64

**Pull request merged**
