### PR TITLE
Remove redundant condition

### PR DESCRIPTION
**Pull request by bkutil**
Remove redundant if. Checking once for the same thing should be enough for everybody. Also add test for time range options.

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmajda

**Comment by dmajda** [comment]
+1 with green tests

**Comment by bkutil** [comment]
The test failures are unrelated - they depend on the new adapter api/ast updates being in master.

**Comment by dmajda** [comment]
Unconditional +1 then.

**Comment by bkutil** [comment]
Thanks

**Pull request merged**
