### PR TITLE
Add order by clause support

### PR DESCRIPTION
**Pull request by bkutil**
Add support and tests for order by and order direction options/queries and add tests. For now, support only ordering using a single field.

refs: #39

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @demmer

**Comment by bkutil** [comment]
Rebased.

**Comment by dmajda** [comment]
(Reviewed per @bkutil’s request.)

Looks good technically, I just wonder about the API. I don’t like the idea of two options specifying the ordering. When multiple ordering criteria get implemented, there would presumably two arrays to coordinate, which is fragile.

What about something like this instead:

```
read influx ... -orderBy "foo"
read influx ... -orderBy { field: "foo", direction: "desc" }
read influx ... -orderBy "foo", "bar"
read influx ... -orderBy { field: "foo", direction: "desc" }, { field: "bar", direction: "asc" }
```

In this scheme, the canonical value of the option is an array of objects with `field` and `direction` properties. Any non-array value is treated like a one-element array. And if an array element is not an object but a string, it is treated like an object with `field` set to that string and `direction` set to `"asc"`. All other values are invalid.

An alternative is to use a two-element array instead of an object:

```
read influx ... -orderBy "foo"
read influx ... -orderBy [ "foo", "desc" ]
read influx ... -orderBy "foo", "bar"
read influx ... -orderBy [ "foo", "desc" ], [ "bar", "asc" ]
```

It’s shorter, but I find it less obvious and there is an ambiguity (two fields vs. field and a direction).

@bkutil @demmer What do you think?

**Comment by dmajda** [comment]
One more thing: docs?

**Comment by bkutil** [comment]
> One more thing: docs?

Good point, the README update is missing. I'll work on the PR after the 0.4.0 release.

**Comment by dmehra** [comment]
Is this meant as a stepping stone to optimizing `sort FIELDNAME [-desc]`?

**Comment by demmer** [comment]
> Is this meant as a stepping stone to optimizing `sort FIELDNAME [-desc]`?

That was my question as well -- it seems like this is setting a bad precedent since there's no reason why we would treat `sort` following `read` any differently from `head` or `tail` or `reduce`.

My preference would be that since we don't have any compelling need for this feature as written, that we put this on hold and implement it the "right way" with optimization.

**Comment by bkutil** [comment]
> Is this meant as a stepping stone to optimizing -sort

@dmehra In fact, it was meant for optimizing 'head' and 'tail'. See #41 and #39.

> That was my question as well -- it seems like this is setting a bad precedent since there's no reason why we would treat sort following read any differently from...

@demmer could you please elaborate?

> My preference would be that since we don't have any compelling need for this feature as written

I should've included a more visible link to the #39 - a summary tracking bug for optimizing `head` and `tail`.

**Comment by dmehra** [comment]
I still don't follow, do we intend to expose `read influx -orderBy 'foo'` or `read influx | sort foo` which is idiomatic juttle? Based on the earlier comments in this PR it's the former, `-orderBy` as a read option; I can see how the ability to sort (by time) is needed for optimizing `head` and `tail`, but don't see the connection with adding an orderBy option to read.

**Comment by bkutil** [comment]
Ok, we clarified the context on slack. There indeed is no connection between adding another option and the optimisations. I didn't realise exposing it is not necessary - and introducing it wasn't intentional. Will rework the PR so it keeps the optimisations in, but doesn't add new options to the public interface.

**Comment by bkutil** [comment]
Closing for now - as the change is internal and related to the optimisations, I'll move the commit into #41.

**Pull request closed without merging**
