### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by bkutil**
Start tracking test coverage using istanbul.

Fixes: #57

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmehra @rlgomes @dmajda

**Comment by bkutil** [comment]
Side note - All components are tested on two levels - unit tests and then integration tests which perform actual queries against a live database. What could be improved is trying to provoke code into various failures (i.e. not testing only happy paths).

**Comment by rlgomes** [comment]
+1

**Comment by bkutil** [comment]
@rlgomes thanks :) Should I update the summary issue?

**Comment by dmehra** [comment]
Yes, thanks @bkutil, and file a new issue to add tests for missing branch coverage

**Comment by bkutil** [comment]
@dmehra updated

**Pull request merged**
