### PR TITLE
0.4.1 fixes

### PR DESCRIPTION
**Pull request by demmer**
Backport bug fixes into the 0.4.x branch.

### CODE REVIEW

**Comment by demmer** [comment]
@bkutil @dmehra  Will merge and release a 0.4.1 release on green build.

**Comment by bkutil** [comment]
+1

**Comment by demmer** [comment]
@bkutil pushed another commit so travis installs the right version of juttle.

**Comment by demmer** [comment]
Tests all pass locally -- it looks like for some reason travis isn't working right since it isn't talking to the right influx host. I'm going to merge and publish 0.4.1.

**Comment by bkutil** [comment]
Yeah, I changed the way how `scripts/docker.sh` works and removed the unused containers :<

Cherry-picking https://github.com/juttle/juttle-influx-adapter/commit/aaa9882b1dffdaa486ccc3adb10031bb7d7394ce and passing influx version via travis ENV should fix it. Should I do that?

**Comment by demmer** [comment]
Sure -- I'd be fine if you do that straight on the 0.4.x branch.

On Wed, Feb 24, 2016 at 11:05 PM, Balázs Kutil <notifications@github.com>
wrote:

> Yeah, I changed the way how scripts/docker.sh works and removed the
> unused containers :<
>
> Cherry-picking aaa9882
> <https://github.com/juttle/juttle-influx-adapter/commit/aaa9882b1dffdaa486ccc3adb10031bb7d7394ce>
> and passing influx version via travis ENV should fix it. Should I do that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juttle/juttle-influx-adapter/pull/98#issuecomment-188643844>
> .
>



-- 
Michael Demmer
Jut - CTO / VP Engineering
demmer@jut.io

**Pull request merged**
