### PR TITLE
new adapter api

### LINKED ISSUE #43: port to the new adapter read / write API
The implementation should be updated to use the new adapter API implemented in https://github.com/juttle/juttle/pull/248. 

In addition to cleaning up the implementation, this will make it easier to support a "live" mode for reading in which the `read` proc will periodically call into the adapter to fetch newly arriving points.

### PR DESCRIPTION
**Pull request by demmer**
Port the influx adapter to the new API for read and write.

In addition, fix the write behavior so that instead of declaring the write to be done after the first batch of points is written, the adapter tracks the outstanding write operations and only declares done once all have completed and eof has been received.

Fixes #43

### CODE REVIEW

**Comment by demmer** [comment]
@bkutil

**Comment by bkutil** [comment]
From the code/implementation point of view, looks good.

One thing that I'd like to handle in a separate PR is the ES5->ES6 switch, unless you want to do it across the whole repo in this PR :) 

Also, separating the 'cleanups' unrelated to read API change into small atomic commits would be great, as it would emphasise the bare minimum needed to update to the new Read API. They can be still part of this PR.

What is needed to get `limit` working in `read`?

I reran the tests and they're still failing, so it's not an intermittent failure. Any ideas what might be wrong or missing?

**Comment by demmer** [comment]
@bkutil I pushed another commit to update package.json and travis to use the latest juttle 0.4.0 release.

Hopefully that should make travis more reliable at least.

As far as your other comments, as per our discussion offline I'm ok if you want to take this branch and do additional changes to it. I personally feel like it's ok to merge as-is (once tests are reliably passing) but I'm also ok if you want to change the ES5/ES6 approach.

**Comment by bkutil** [comment]
Superseded by #51, which is based on this.

**Pull request closed without merging**
