### PR TITLE
Add performance tests for influx serialization

### PR DESCRIPTION
**Pull request by bkutil**
The benchmarks can be run using `npm run-script -s perf`.

### CODE REVIEW

**Comment by bkutil** [comment]
After rewriting the `toInflux` serialisation, the throughput improved nicely:

before:
```
serializer.toInflux x 33,620 ops/sec ±3.14% (84 runs sampled)
AdapterWrite.serialize, 1k points/call x 30.77 ops/sec ±3.93% (50 runs sampled)
AdapterWrite.write, stubbed request, 1k points/call x 28.59 ops/sec ±5.87% (65 runs sampled)
AdapterWrite.write, live request, 1k points/call x 19.88 ops/sec ±7.36% (49 runs sampled)
```

after:
```
serializer.toInflux x 152,627 ops/sec ±0.69% (92 runs sampled)
AdapterWrite.serialize, 1k points/call x 129 ops/sec ±1.01% (71 runs sampled)
AdapterWrite.write, stubbed request, 1k points/call x 128 ops/sec ±2.00% (75 runs sampled)
AdapterWrite.write, live request, 1k points/call x 50.01 ops/sec ±7.86% (57 runs sampled)
```

**Comment by bkutil** [comment]
cc: @dmehra @demmer

**Comment by dmehra** [comment]
Sorry, been sick, behind on PRs, passing over to @rlgomes

**Comment by rlgomes** [comment]
Quick glance this looks great, a few suggestions come to mind:

 1. Why not make the performance tests mocha tests ? you can use `mocha-logger` to output the performance numbers instead of console.log and at least running things is a bit "simpler" by doing `gulp performance` (of course we need to up the timeouts to handle the fact these run for longer than a regular mocha test). 
 2. wonder if we can also start saving the results of each run to a "peformance/results/v0.5.txt" where we rerun the tests in a somewhat controlled environment and record the results there just for tracking ? Depending on how long these take maybe our controlled environment would be to run and save the output from Travis itself ? (we can discuss this offline)
 3. We should definitely apply this on our other adapters so we can give people a pretty good idea of what to expect when read/writing to a given adapter. I would say lets open issues on each of the existing adapters if others are in agreement that this would be a nice thing to have in each adapter and now that I'm writing this we should also do the same for the juttle engine itself and that way we'd know how performant the base engine is at doing some simple point pushing through the pipeline.

None of the above need to block this but I do think we need to figure out how we go about rerunning these in a way that can help us identify significant performance regressions before we'd ship something.

**Comment by bkutil** [comment]
Will merge on green.

**Pull request merged**
