### PR TITLE
ES6

### PR DESCRIPTION
**Pull request by bkutil**

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmajda @demmer

**Comment by dmajda** [comment]
I think we need some agreement on usage of various ES6 features before going forward with changes like this. My opinions:

  * **Native methods.** First, using e.g. `Array.prototype.map` instead of `_.map` is not really an ES6 thing, we could have done this already (and we sometimes did). In the past, I tended to use native methods where possible and only using `_` where the native method doesn’t exist. But I ended up reversing my position and started using `_` everywhere. My reasons were:
    * It makes code more consistent overall.
    * Code using the `_` methods is shorter.
    * One doesn’t need to need to think about whether/where each native method is supported.
    * Multiple `_` calls are chainable using `_.chain`.

  * **Using `=>` for function expressions.** Not strong opinion here, I just don’t want to think about the choice between `function` and `=>` much when writing code. Given that `=>`’s have the right `this` semantics, I’d be inclined to using them everywhere (for all function expressions).

  * **Shorthand properties.** I actually don’t like them at all, but this is more of an aesthetic choice, not something rational (and it also ties to how classes are done in ES6). Since they exist in the language and they have no adverse effect, let’s just use them where possible.

  * **Template strings.** Let’s just use them.

Beside this, we need an agreement about how to do the conversion. Obviously, for a small piece of code like this adapter you could do it at once, but I’m less convinced we should invest the energy to do all the changes at once on a wider scale. On the other hand, some of the conversions are definitely amenable to automation, similarly to the ES6 classes conversion.

---

To the PR: It would be great to change just one kind of things per commit, otherwise the changes are hard to review (and to revert, should we decide we don’t want to use some features).

**Comment by bkutil** [comment]
> To the PR: It would be great to change just one kind of things per commit, otherwise the changes are hard to review

Ok, I assume this is primarily about the first commit. I'll make sure that commits change only a single aspect of the syntax and split them accordingly.

> I think we need some agreement on usage of various ES6 features before going forward with changes like this. My opinions:

As this will be a subject of bike-, trike- and quadruple-shedding, I'd suggest adhering to a widely used third party set of lint rules, for example [airbnb's](https://github.com/airbnb/javascript), then relaxing/modifying those checks which prove to be too restrictive. This was actually an approach taken in this PR and worked fairly well.

> Beside this, we need an agreement about how to do the conversion. Obviously, for a small piece of code like this adapter you could do it at once, but I’m less convinced we should invest the energy to do all the changes at once on a wider scale.

I completely agree here. The switch is probably impossible to do at once for core, and perhaps not even necessary - I think the classes were the only thing affecting the whole project (core + adapters). As for other changes, automating this looks like a way to go.

**Comment by bkutil** [comment]
I split the first commit so it deals exclusively with switch to `=>` - the rest were property shorthand modifications and were added with the rest.

**Comment by dmajda** [comment]
+1 with the comments addressed

**Comment by bkutil** [comment]
Unrelated changes were split into separate commits. Will merge on green.

**Pull request merged**
