### PR TITLE
reorganize the source code

### PR DESCRIPTION
**Pull request by demmer**
Instead of having all the code in the top level index file, split out
read and write into separate files and add a simple shared module to
stash the config.

Also made a couple minor changes to the tests in order to allow the
db host to be specified in the environment and thereby easily runnable
inside a container.

### CODE REVIEW

**Comment by demmer** [comment]
@bkutil

**Comment by bkutil** [comment]
The test failures are caused by `JuttleMoment.compare change` - #29 should fix that.

**Comment by bkutil** [comment]
I rebased the PR on top of #29 and cleaned up the test modification a bit (I think we should be able to pass influx port as well).

Otherwise, looks good. I'll merge on green - thanks :)

**Comment by bkutil** [comment]
There were some test failures, but re-running the builds fixed them (they were unrelated to the code). Merging.

**Pull request merged**
